---
dest: "~/.dotfiles"
archive: "~/tmp/dotfiles.tar.gz"
tasks:
  - src: "~/.startup.sh"
#  - src: "~/.fehbg"
  - src: "~/.prof"
  - src: "~/.zshrc"
  - src: "~/.xinitrc"
  - src: "~/.dotfiles.yml"
  - src: "~/.radare2rc"
    
  - src: "~/.config/i3/config"
    subdir: ".config/i3"

  - src: "~/.config/polybar/launch.sh"
    subdir: ".config/polybar"

  - src: "~/.config/polybar/config"
    subdir: ".config/polybar"

  - src: "~/.config/spicetify/Themes/Ziro/"
    subdir: ".config/spicetify/Themes/Ziro"

  - src: "~/.config/spicetify/Extensions/fullAppDisplay.js"
    subdir: ".config/spicetify/Extensions"

  - src: "~/.config/spicetify/config-xpui.ini"
    subdir: ".config/spicetify"

  - src: "~/.config/picom/picom.conf"
    subdir: ".config/picom"

  - src: "~/.config/kitty/kitty.conf"
    subdir: ".config/kitty"

  - src: "~/.config/rofi/"
    subdir: ".config/rofi"

  - src: "~/.config/mpv/"
    subdir: ".config/mpv"

  - src: "~/bin/conf"
    subdir: "bin"

  - src: "~/bin/change-wallpaper"
    subdir: "bin"

  - src: "~/bin/sp"
    subdir: "bin"

  - src: "~/bin/add-nordvpn.sh"
    subdir: "bin"

  - src: "~/bin/i3-get-window-criteria"
    subdir: "bin"

  - src: "~/bin/ip-sweep"
    subdir: "bin"

  - src: "~/bin/mpvcontrol.sh"
    subdir: "bin"

  - src: "~/bin/sync-dotfiles"
    subdir: "bin"
